name: grocery_shop_flutter
description: An example grocery shop UI.

version: 1.0.12

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.21.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
      - family: JosefinSans
        fonts:
          - asset: fonts/JosefinSans.ttf

  assets:
      - assets/images/